### PR TITLE
Bourbon and neat

### PR DESCRIPTION
**Pull request by martinisoft**
This PR massively upgrades the style frameworks to include [Bourbon](http://bourbon.io/), [Neat](http://neat.bourbon.io/), and [Foundation](http://foundation.zurb.com/). Neat will provide a nice grid system that uses Sass Mixin's instead of lots of crazy selectors.

There is also some upgrades to Rails, Devise, and Postmark to keep things up to date. I've also included some sample webfonts that closely match the title image. The design is very bare-bones, but can be built-up over time easily.

2013-08-09 at 4 11 pm

Updated sign-in page:

2013-08-09 at 4 11 pm

### CODE REVIEW

**Comment by martinisoft** [comment]
Should be a little bit better with a smaller grid.

2013-08-09 at 4 20 pm

**Comment by Aevin1387** [comment]
The sign up page looks a bit weird.
2013-08-09 at 5 03 pm

**Comment by martinisoft** [comment]
@Aevin1387 looks like the hints. don't have the styles in for that yet. Wonder if Foundation has that.

**Comment by Aevin1387** [comment]
Foundation doesn't support hints. Maybe [hint.css?](http://kushagragour.in/lab/hint/)

**Comment by martinisoft** [comment]
After much collaboration and discussion, this is ready to ship!

**Pull request merged**
